package com.shq.entities;
// Generated 10-feb-2018 21:58:23 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Almacen generated by hbm2java
 */
@Entity
@Table(name = "ALMACEN", catalog = "shq")
public class Almacen implements java.io.Serializable {

	private int idAlmacen;
	private String direccion;
	private String nombre;
	private String tipoAlmacen;
	private Date fechaFinAlmacen;
	private String nombreContacto;
	private String telContacto;
	private String correoContacto;
	private String horarioAtencion;

	public Almacen() {
	}

	public Almacen(int idAlmacen) {
		this.idAlmacen = idAlmacen;
	}

	public Almacen(int idAlmacen, String direccion, String nombre, String tipoAlmacen, Date fechaFinAlmacen,
			String nombreContacto, String telContacto, String correoContacto, String horarioAtencion) {
		this.idAlmacen = idAlmacen;
		this.direccion = direccion;
		this.nombre = nombre;
		this.tipoAlmacen = tipoAlmacen;
		this.fechaFinAlmacen = fechaFinAlmacen;
		this.nombreContacto = nombreContacto;
		this.telContacto = telContacto;
		this.correoContacto = correoContacto;
		this.horarioAtencion = horarioAtencion;
	}

	@Id
	 @GeneratedValue(strategy = GenerationType.AUTO) 
	@Column(name = "id_almacen", unique = true, nullable = false)
	public int getIdAlmacen() {
		return this.idAlmacen;
	}

	public void setIdAlmacen(int idAlmacen) {
		this.idAlmacen = idAlmacen;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo_almacen", length = 45)
	public String getTipoAlmacen() {
		return this.tipoAlmacen;
	}

	public void setTipoAlmacen(String tipoAlmacen) {
		this.tipoAlmacen = tipoAlmacen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin_almacen", length = 19)
	public Date getFechaFinAlmacen() {
		return this.fechaFinAlmacen;
	}

	public void setFechaFinAlmacen(Date fechaFinAlmacen) {
		this.fechaFinAlmacen = fechaFinAlmacen;
	}

	@Column(name = "nombre_contacto", length = 45)
	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	@Column(name = "tel_contacto", length = 45)
	public String getTelContacto() {
		return this.telContacto;
	}

	public void setTelContacto(String telContacto) {
		this.telContacto = telContacto;
	}

	@Column(name = "correo_contacto", length = 45)
	public String getCorreoContacto() {
		return this.correoContacto;
	}

	public void setCorreoContacto(String correoContacto) {
		this.correoContacto = correoContacto;
	}

	@Column(name = "horario_atencion", length = 45)
	public String getHorarioAtencion() {
		return this.horarioAtencion;
	}

	public void setHorarioAtencion(String horarioAtencion) {
		this.horarioAtencion = horarioAtencion;
	}

}
