package com.shq.entities;
// Generated 15-mar-2018 13:33:00 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApartadosCotizacion generated by hbm2java
 */
@Entity
@Table(name = "apartados_cotizacion", catalog = "shq")
public class ApartadosCotizacion implements java.io.Serializable {

	private Long id;
	private long cantidad;
	private Producto producto;
	private String lote;
	private boolean activo;
	private SolCotizacion solCotizacion;

	public ApartadosCotizacion() {
	}

	public ApartadosCotizacion(long id, long cantidad, Producto producto, String lote, boolean activo, SolCotizacion solCotizacion) {
		this.id = id;
		this.cantidad = cantidad;
		this.producto = producto;
		this.lote = lote;
		this.activo = activo;
		this.solCotizacion = solCotizacion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) 
	@Column(name = "id", unique = true, nullable = false, precision = 11, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "cantidad", nullable = false, precision = 11, scale = 0)
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}
	

	@Column(name = "lote", nullable = false, length = 45)
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@Column(name = "activo", nullable = false)
	public boolean getActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "id_solicitud", nullable = false)
	public SolCotizacion getSolCotizacion() {
		return solCotizacion;
	}

	public void setSolCotizacion(SolCotizacion solCotizacion) {
		this.solCotizacion = solCotizacion;
	}

}
