package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArchivosMovInv generated by hbm2java
 */
@Entity
@Table(name = "ARCHIVOS_MOV_INV", catalog = "shq")
public class ArchivosMovInv implements java.io.Serializable {

	private int id;
	private String extension;
	private String nombre;
	private String tipo;
	private String url;
	private Integer idMovInventario;

	public ArchivosMovInv() {
	}

	public ArchivosMovInv(int id) {
		this.id = id;
	}

	public ArchivosMovInv(int id, String extension, String nombre, String tipo, String url, Integer idMovInventario) {
		this.id = id;
		this.extension = extension;
		this.nombre = nombre;
		this.tipo = tipo;
		this.url = url;
		this.idMovInventario = idMovInventario;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "extension")
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ID_MOV_INVENTARIO")
	public Integer getIdMovInventario() {
		return this.idMovInventario;
	}

	public void setIdMovInventario(Integer idMovInventario) {
		this.idMovInventario = idMovInventario;
	}

}
