package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatBancosId generated by hbm2java
 */
@Embeddable
public class CatBancosId implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private String razonSocial;

	public CatBancosId() {
	}

	public CatBancosId(Integer codigo, String nombre, String razonSocial) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.razonSocial = razonSocial;
	}

	@Column(name = "CODIGO")
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "NOMBRE", length = 65535)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "RAZON_SOCIAL", length = 65535)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatBancosId))
			return false;
		CatBancosId castOther = (CatBancosId) other;

		return ((this.getCodigo() == castOther.getCodigo()) || (this.getCodigo() != null
				&& castOther.getCodigo() != null && this.getCodigo().equals(castOther.getCodigo())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getRazonSocial() == castOther.getRazonSocial())
						|| (this.getRazonSocial() != null && castOther.getRazonSocial() != null
								&& this.getRazonSocial().equals(castOther.getRazonSocial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getRazonSocial() == null ? 0 : this.getRazonSocial().hashCode());
		return result;
	}

}
