package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatBancos generated by hbm2java
 */
@Entity
@Table(name = "cat_bancos", catalog = "shq")
public class CatBancos implements java.io.Serializable {

	private CatBancosId id;

	public CatBancos() {
	}

	public CatBancos(CatBancosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codigo", column = @Column(name = "CODIGO")),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 65535)),
			@AttributeOverride(name = "razonSocial", column = @Column(name = "RAZON_SOCIAL", length = 65535)) })
	public CatBancosId getId() {
		return this.id;
	}

	public void setId(CatBancosId id) {
		this.id = id;
	}

}
