package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatPaises generated by hbm2java
 */
@Entity
@Table(name = "cat_paises", catalog = "shq")
public class CatPaises implements java.io.Serializable {

	private CatPaisesId id;

	public CatPaises() {
	}

	public CatPaises(CatPaisesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 65535)),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 65535)),
			@AttributeOverride(name = "nom", column = @Column(name = "nom", length = 65535)),
			@AttributeOverride(name = "iso", column = @Column(name = "iso", length = 65535)),
			@AttributeOverride(name = "isoTres", column = @Column(name = "iso_tres", length = 65535)),
			@AttributeOverride(name = "phoneCode", column = @Column(name = "phone_code")) })
	public CatPaisesId getId() {
		return this.id;
	}

	public void setId(CatPaisesId id) {
		this.id = id;
	}

}
