package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatSepomex generated by hbm2java
 */
@Entity
@Table(name = "CAT_SEPOMEX", catalog = "shq")
public class CatSepomex implements java.io.Serializable {

	private CatSepomexId id;

	public CatSepomex() {
	}

	public CatSepomex(CatSepomexId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "DCodigo", column = @Column(name = "d_codigo", length = 65535)),
			@AttributeOverride(name = "DAsenta", column = @Column(name = "d_asenta", length = 65535)),
			@AttributeOverride(name = "DTipoAsenta", column = @Column(name = "d_tipo_asenta", length = 65535)),
			@AttributeOverride(name = "DMnpio", column = @Column(name = "D_mnpio", length = 65535)),
			@AttributeOverride(name = "DEstado", column = @Column(name = "d_estado", length = 65535)),
			@AttributeOverride(name = "DCiudad", column = @Column(name = "d_ciudad", length = 65535)),
			@AttributeOverride(name = "DCp", column = @Column(name = "d_CP", length = 65535)),
			@AttributeOverride(name = "CEstado", column = @Column(name = "c_estado", length = 65535)),
			@AttributeOverride(name = "COficina", column = @Column(name = "c_oficina", length = 65535)),
			@AttributeOverride(name = "CCp", column = @Column(name = "c_CP", length = 65535)),
			@AttributeOverride(name = "CTipoAsenta", column = @Column(name = "c_tipo_asenta", length = 65535)),
			@AttributeOverride(name = "CMnpio", column = @Column(name = "c_mnpio", length = 65535)),
			@AttributeOverride(name = "idAsentaCpcons", column = @Column(name = "id_asenta_cpcons", length = 65535)),
			@AttributeOverride(name = "DZona", column = @Column(name = "d_zona", length = 65535)),
			@AttributeOverride(name = "CCveCiudad", column = @Column(name = "c_cve_ciudad", length = 65535)) })
	public CatSepomexId getId() {
		return this.id;
	}

	public void setId(CatSepomexId id) {
		this.id = id;
	}

}
