package com.shq.entities;
// Generated 13-nov-2017 12:00:01 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClienteDomicilio generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE_DOMICILIO", catalog = "shq")
public class ClienteDomicilio implements java.io.Serializable {

	private int id;
	private int idCliente;
	private int idPais;
	private int idEstado;
	private int idMunicipio;
	private int idCp;
	private String calle;
	private String numExt;
	private String numInt;
	private boolean principal;

	public ClienteDomicilio() {
	}

	public ClienteDomicilio(int id, int idCliente, int idPais, int idEstado, int idMunicipio, int idCp, String calle,
			String numExt, boolean principal) {
		this.id = id;
		this.idCliente = idCliente;
		this.idPais = idPais;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idCp = idCp;
		this.calle = calle;
		this.numExt = numExt;
		this.principal = principal;
	}

	public ClienteDomicilio(int id, int idCliente, int idPais, int idEstado, int idMunicipio, int idCp, String calle,
			String numExt, String numInt, boolean principal) {
		this.id = id;
		this.idCliente = idCliente;
		this.idPais = idPais;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idCp = idCp;
		this.calle = calle;
		this.numExt = numExt;
		this.numInt = numInt;
		this.principal = principal;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ID_CLIENTE", nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "ID_PAIS", nullable = false)
	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	@Column(name = "ID_ESTADO", nullable = false)
	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "ID_MUNICIPIO", nullable = false)
	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@Column(name = "ID_CP", nullable = false)
	public int getIdCp() {
		return this.idCp;
	}

	public void setIdCp(int idCp) {
		this.idCp = idCp;
	}

	@Column(name = "CALLE", nullable = false, length = 400)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "NUM_EXT", nullable = false, length = 45)
	public String getNumExt() {
		return this.numExt;
	}

	public void setNumExt(String numExt) {
		this.numExt = numExt;
	}

	@Column(name = "NUM_INT", length = 45)
	public String getNumInt() {
		return this.numInt;
	}

	public void setNumInt(String numInt) {
		this.numInt = numInt;
	}

	@Column(name = "PRINCIPAL", nullable = false)
	public boolean isPrincipal() {
		return this.principal;
	}

	public void setPrincipal(boolean principal) {
		this.principal = principal;
	}

}
