package com.shq.entities;
// Generated 28-feb-2018 1:50:21 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CotizarVw generated by hbm2java
 */
@Entity
@Table(name = "cotizar_vw", catalog = "shq")
public class CotizarVw implements java.io.Serializable {

	private CotizarVwId id;

	public CotizarVw() {
	}

	public CotizarVw(CotizarVwId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cantidad", column = @Column(name = "CANTIDAD", precision = 34, scale = 0)),
			@AttributeOverride(name = "costoProm", column = @Column(name = "COSTO_PROM", precision = 23, scale = 6)),
			@AttributeOverride(name = "producto", column = @Column(name = "producto")) })
	public CotizarVwId getId() {
		return this.id;
	}

	public void setId(CotizarVwId id) {
		this.id = id;
	}

}
