package com.shq.entities;
// Generated 09-abr-2018 5:40:18 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CotizacionProveedor generated by hbm2java
 */
@Entity
@Table(name = "cotizacion_proveedor", catalog = "shq")
public class CotizacionProveedor implements java.io.Serializable {

	private BigDecimal id;
	private Externo proveedor;
	private SolCotizacion solCotizacion;
	private String entregaDomicilio;
	private Set<ProductoCotProveedor> productoCotProveedors = new HashSet<ProductoCotProveedor>(0);
	private List<ProductoCotProveedor> listaProductoCotProveedors = new ArrayList<ProductoCotProveedor>();
	private Boolean enviadaVentas;
	private Boolean enviadaCompras;
	private Boolean enviadaCliente;

	public CotizacionProveedor() {
	}

	public CotizacionProveedor(BigDecimal id, Externo proveedor, SolCotizacion solCotizacion,String entregaDomicilio) {
		this.id = id;
		this.proveedor = proveedor;
		this.solCotizacion = solCotizacion;
		this.entregaDomicilio = entregaDomicilio;
	}

	public CotizacionProveedor(BigDecimal id, Externo proveedor, SolCotizacion solCotizacion,
			Set<ProductoCotProveedor> productoCotProveedors, String entregaDomicilio) {
		this.id = id;
		this.proveedor = proveedor;
		this.solCotizacion = solCotizacion;
		this.productoCotProveedors = productoCotProveedors;
		this.entregaDomicilio = entregaDomicilio;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) 
	@Column(name = "id", unique = true, nullable = false, precision = 11, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.EAGER,cascade = {CascadeType.MERGE})
	@JoinColumn(name = "id_externo", nullable = false)
	public Externo getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Externo proveedor) {
		this.proveedor = proveedor;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade = {CascadeType.MERGE})
	@JoinColumn(name = "id_solicitud", nullable = false)
	public SolCotizacion getSolCotizacion() {
		return this.solCotizacion;
	}

	public void setSolCotizacion(SolCotizacion solCotizacion) {
		this.solCotizacion = solCotizacion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "cotizacionProveedor")
	public Set<ProductoCotProveedor> getProductoCotProveedors() {
		return this.productoCotProveedors;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "cotizacionProveedor")
	public List<ProductoCotProveedor> getListaProductoCotProveedors() {
		return listaProductoCotProveedors;
	}
	

	public void setProductoCotProveedors(Set<ProductoCotProveedor> productoCotProveedors) {
		this.productoCotProveedors = productoCotProveedors;
	}
	
	public void setListaProductoCotProveedors(List<ProductoCotProveedor> listaProductoCotProveedors) {
		this.listaProductoCotProveedors = listaProductoCotProveedors;
	}

	
	@Column(name = "entrega_domicilio", length = 45)
	public String getEntregaDomicilio() {
		return entregaDomicilio;
	}

	public void setEntregaDomicilio(String entregaDomicilio) {
		this.entregaDomicilio = entregaDomicilio;
	}
	
	@Column(name = "enviada_ventas")
	public Boolean getEnviadaVentas() {
		return enviadaVentas;
	}

	public void setEnviadaVentas(Boolean enviadaVentas) {
		this.enviadaVentas = enviadaVentas;
	}

	@Column(name = "enviada_compras")
	public Boolean getEnviadaCompras() {
		return enviadaCompras;
	}

	public void setEnviadaCompras(Boolean enviadaCompras) {
		this.enviadaCompras = enviadaCompras;
	}

	@Column(name = "enviada_cliente")
	public Boolean getEnviadaCliente() {
		return enviadaCliente;
	}

	public void setEnviadaCliente(Boolean enviadaCliente) {
		this.enviadaCliente = enviadaCliente;
	}

}
