package com.shq.entities;
// Generated 28-feb-2018 1:50:21 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CotizarVwId generated by hbm2java
 */
@Embeddable
public class CotizarVwId implements java.io.Serializable {

	private BigInteger cantidad;
	private BigInteger costoProm;
	private String producto;

	public CotizarVwId() {
	}
	
	public CotizarVwId(BigInteger cantidad, String producto) {
		this.cantidad = cantidad;
		this.producto = producto;
	}

	public CotizarVwId(BigInteger cantidad, BigInteger costoProm, String producto) {
		this.cantidad = cantidad;
		this.costoProm = costoProm;
		this.producto = producto;
	}

	@Column(name = "CANTIDAD", precision = 34, scale = 0)
	public BigInteger getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigInteger cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "COSTO_PROM", precision = 23, scale = 6)
	public BigInteger getCostoProm() {
		return this.costoProm;
	}

	public void setCostoProm(BigInteger costoProm) {
		this.costoProm = costoProm;
	}

	@Column(name = "producto")
	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CotizarVwId))
			return false;
		CotizarVwId castOther = (CotizarVwId) other;

		return ((this.getCantidad() == castOther.getCantidad()) || (this.getCantidad() != null
				&& castOther.getCantidad() != null && this.getCantidad().equals(castOther.getCantidad())))
				&& ((this.getCostoProm() == castOther.getCostoProm()) || (this.getCostoProm() != null
						&& castOther.getCostoProm() != null && this.getCostoProm().equals(castOther.getCostoProm())))
				&& ((this.getProducto() == castOther.getProducto()) || (this.getProducto() != null
						&& castOther.getProducto() != null && this.getProducto().equals(castOther.getProducto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		result = 37 * result + (getCostoProm() == null ? 0 : this.getCostoProm().hashCode());
		result = 37 * result + (getProducto() == null ? 0 : this.getProducto().hashCode());
		return result;
	}

}
