package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CuentaBanco generated by hbm2java
 */
@Entity
@Table(name = "CUENTA_BANCO", catalog = "shq")
public class CuentaBanco implements java.io.Serializable {

	private Integer id;
	private String numCuenta;
	private String clabe;
	private String banco;
	private String otroBanco;
	private Externo externo;

	public CuentaBanco() {
	}

	public CuentaBanco(Integer id) {
		this.id = id;
	}

	public CuentaBanco(Integer id, String numCuenta, String clabe, String banco, String otroBanco,
			Externo externo) {
		this.id = id;
		this.numCuenta = numCuenta;
		this.clabe = clabe;
		this.banco = banco;
		this.otroBanco = otroBanco;
		this.externo = externo;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NUM_CUENTA", length = 45)
	public String getNumCuenta() {
		return this.numCuenta;
	}

	public void setNumCuenta(String numCuenta) {
		this.numCuenta = numCuenta;
	}

	@Column(name = "CLABE", length = 45)
	public String getClabe() {
		return this.clabe;
	}

	public void setClabe(String clabe) {
		this.clabe = clabe;
	}

	@Column(name = "BANCO", length = 45)
	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	@Column(name = "OTRO_BANCO", length = 45)
	public String getOtroBanco() {
		return this.otroBanco;
	}

	public void setOtroBanco(String otroBanco) {
		this.otroBanco = otroBanco;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_externo")
	public Externo getExterno() {
		return this.externo;
	}

	public void setExterno(Externo externo) {
		this.externo = externo;
	}

}
