package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domicilio generated by hbm2java
 */
@Entity
@Table(name="domicilio"
    ,catalog="shq"
)
public class Domicilio  implements Serializable {


     private BigDecimal idDomicilio;
     private String codPais;
     private String codEstado;
     private String codMunicipio;
     private String codColonia;
     private String cp;
     private String calle;
     private String numExt;
     private String numInt;
     private Boolean principal;
     private String referencias;
     private String entreCalles;
     private Integer idAlmacen;
     private BigDecimal idExterno;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Externo> externos = new HashSet<Externo>(0);

    public Domicilio() {
    }

	
    public Domicilio(BigDecimal idDomicilio, String codPais, String codEstado, String codMunicipio,String codColonia, String cp, String calle, String numExt, Boolean principal, String referencias, BigDecimal idExterno) {
        this.idDomicilio = idDomicilio;
        this.codPais = codPais;
        this.codEstado = codEstado;
        this.codMunicipio = codMunicipio;
        this.codColonia = codColonia;
        this.cp = cp;
        this.calle = calle;
        this.numExt = numExt;
        this.principal = principal;
        this.referencias = referencias;
        this.idExterno = idExterno;
    }
    public Domicilio(BigDecimal idDomicilio, String codPais, String codEstado, String codMunicipio, String codColonia, String cp, String calle, String numExt, String numInt, Boolean principal, String referencias, String entreCalles, Integer idAlmacen, BigDecimal idExterno, Set<Empleado> empleados, Set<Externo> externos) {
       this.idDomicilio = idDomicilio;
       this.codPais = codPais;
       this.codEstado = codEstado;
       this.codMunicipio = codMunicipio;
       this.codColonia = codColonia;
       this.cp = cp;
       this.calle = calle;
       this.numExt = numExt;
       this.numInt = numInt;
       this.principal = principal;
       this.referencias = referencias;
       this.entreCalles = entreCalles;
       this.idAlmacen = idAlmacen;
       this.idExterno = idExterno;
       this.empleados = empleados;
       this.externos = externos;
    }
   
     @Id 

    
    @Column(name="id_domicilio", unique=true, nullable=false, precision=50, scale=0)
     @GeneratedValue(strategy = GenerationType.AUTO) 
    public BigDecimal getIdDomicilio() {
        return this.idDomicilio;
    }
    
    public void setIdDomicilio(BigDecimal idDomicilio) {
        this.idDomicilio = idDomicilio;
    }

    
    @Column(name="cod_pais", nullable=false, length=45)
    public String getCodPais() {
        return this.codPais;
    }
    
    public void setCodPais(String codPais) {
        this.codPais = codPais;
    }

    
    @Column(name="cod_estado", nullable=false, length=45)
    public String getCodEstado() {
        return this.codEstado;
    }
    
    public void setCodEstado(String codEstado) {
        this.codEstado = codEstado;
    }

    
    @Column(name="cod_municipio", nullable=false, length=45)
    public String getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(String codMunicipio) {
        this.codMunicipio = codMunicipio;
    }

    
    @Column(name="cp", nullable=false, length=45)
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }

    
    @Column(name="calle", nullable=false, length=400)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="num_ext", nullable=false, length=45)
    public String getNumExt() {
        return this.numExt;
    }
    
    public void setNumExt(String numExt) {
        this.numExt = numExt;
    }

    
    @Column(name="num_int", length=45)
    public String getNumInt() {
        return this.numInt;
    }
    
    public void setNumInt(String numInt) {
        this.numInt = numInt;
    }

    
    @Column(name="principal", nullable=false)
    public Boolean getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(Boolean principal) {
        this.principal = principal;
    }

    
    @Column(name="referencias", nullable=false, length=450)
    public String getReferencias() {
        return this.referencias;
    }
    
    public void setReferencias(String referencias) {
        this.referencias = referencias;
    }

    
    @Column(name="entre_calles", length=450)
    public String getEntreCalles() {
        return this.entreCalles;
    }
    
    public void setEntreCalles(String entreCalles) {
        this.entreCalles = entreCalles;
    }

    
    @Column(name="id_almacen")
    public Integer getIdAlmacen() {
        return this.idAlmacen;
    }
    
    public void setIdAlmacen(Integer idAlmacen) {
        this.idAlmacen = idAlmacen;
    }

    
    @Column(name="id_externo", precision=50, scale=0)
    public BigDecimal getIdExterno() {
        return this.idExterno;
    }
    
    public void setIdExterno(BigDecimal idExterno) {
        this.idExterno = idExterno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="domicilio")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }



@OneToMany(fetch=FetchType.LAZY, mappedBy="domicilio")
    public Set<Externo> getExternos() {
        return this.externos;
    }
    
    public void setExternos(Set<Externo> externos) {
        this.externos = externos;
    }

    @Column(name="cod_colonia", nullable=false, length=45)
	public String getCodColonia() {
		return codColonia;
	}


	public void setCodColonia(String codColonia) {
		this.codColonia = codColonia;
	}




}


