package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Domicilio generated by hbm2java
 */
@Entity
@Table(name="domicilio"
    ,catalog="shq"
)
public class Domicilio  implements Serializable {


     private BigDecimal idDomicilio;
     private String codPais;
     private String pais;
     private String codEstado;
     private String estado;
     private String codMunicipio;
     private String municipio;
     private String codColonia;
     private String colonia;
     private String cp;
     private String calle;
     private String numExt;
     private String numInt;
     private String referencias;
     private String entreCalles;
     private Externo externo;
     private Empleado empleado;
     private boolean activo;
     private boolean fiscal;
     private boolean entrega;
     private boolean secundaria;



    public Domicilio() {
    }

	
    public Domicilio(BigDecimal idDomicilio, String codPais, String codEstado, String codMunicipio,String codColonia, String cp, String calle, String numExt, String referencias, Externo externo) {
        this.idDomicilio = idDomicilio;
        this.codPais = codPais;
        this.codEstado = codEstado;
        this.codMunicipio = codMunicipio;
        this.codColonia = codColonia;
        this.cp = cp;
        this.calle = calle;
        this.numExt = numExt;
        this.referencias = referencias;
        this.externo = externo;
    }
    public Domicilio(BigDecimal idDomicilio, String codPais, String codEstado, String codMunicipio, String codColonia, String cp, String calle, String numExt, String numInt, Boolean principal, String referencias, String entreCalles, Externo externo,Empleado empleado) {
       this.idDomicilio = idDomicilio;
       this.codPais = codPais;
       this.codEstado = codEstado;
       this.codMunicipio = codMunicipio;
       this.codColonia = codColonia;
       this.cp = cp;
       this.calle = calle;
       this.numExt = numExt;
       this.numInt = numInt;
       this.referencias = referencias;
       this.entreCalles = entreCalles;
       this.externo = externo;
       this.empleado = empleado;
    }
   
     @Id 

    
    @Column(name="id_domicilio", unique=true, nullable=false, precision=50, scale=0)
     @GeneratedValue(strategy = GenerationType.AUTO) 
    public BigDecimal getIdDomicilio() {
        return this.idDomicilio;
    }
    
    public void setIdDomicilio(BigDecimal idDomicilio) {
        this.idDomicilio = idDomicilio;
    }

    
    @Column(name="cod_pais", nullable=false, length=45)
    public String getCodPais() {
        return this.codPais;
    }
    
    public void setCodPais(String codPais) {
        this.codPais = codPais;
    }

    
    @Column(name="cod_estado", nullable=false, length=45)
    public String getCodEstado() {
        return this.codEstado;
    }
    
    public void setCodEstado(String codEstado) {
        this.codEstado = codEstado;
    }

    
    @Column(name="cod_municipio", nullable=false, length=45)
    public String getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(String codMunicipio) {
        this.codMunicipio = codMunicipio;
    }

    
    @Column(name="cp", nullable=false, length=45)
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }

    
    @Column(name="calle", nullable=false, length=400)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="num_ext", nullable=false, length=45)
    public String getNumExt() {
        return this.numExt;
    }
    
    public void setNumExt(String numExt) {
        this.numExt = numExt;
    }

    
    @Column(name="num_int", length=45)
    public String getNumInt() {
        return this.numInt;
    }
    
    public void setNumInt(String numInt) {
        this.numInt = numInt;
    }

    
    @Column(name="referencias", nullable=false, length=450)
    public String getReferencias() {
        return this.referencias;
    }
    
    public void setReferencias(String referencias) {
        this.referencias = referencias;
    }

    
    @Column(name="entre_calles", length=450)
    public String getEntreCalles() {
        return this.entreCalles;
    }
    
    public void setEntreCalles(String entreCalles) {
        this.entreCalles = entreCalles;
    }



    @Column(name="cod_colonia", nullable=false, length=45)
	public String getCodColonia() {
		return codColonia;
	}


	public void setCodColonia(String codColonia) {
		this.codColonia = codColonia;
	}
	
	 
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_externo")
    public Externo getExterno() {
        return this.externo;
    }
    
    public void setExterno(Externo externo) {
        this.externo = externo;
    }


    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_empleado")
	public Empleado getEmpleado() {
		return empleado;
	}


	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}


    @Column(name="activo")
	public boolean isActivo() {
		return activo;
	}


	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name="fiscal")
	public boolean isFiscal() {
		return fiscal;
	}


	public void setFiscal(boolean fiscal) {
		this.fiscal = fiscal;
	}

	@Column(name="entrega")
	public boolean isEntrega() {
		return entrega;
	}


	public void setEntrega(boolean entrega) {
		this.entrega = entrega;
	}

	@Column(name="secundaria")
	public boolean isSecundaria() {
		return secundaria;
	}


	public void setSecundaria(boolean secundaria) {
		this.secundaria = secundaria;
	}

	@Column(name="pais")
	public String getPais() {
		return pais;
	}


	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name="estado")
	public String getEstado() {
		return estado;
	}


	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name="municipio")
	public String getMunicipio() {
		return municipio;
	}


	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name="colonia")
	public String getColonia() {
		return colonia;
	}


	public void setColonia(String colonia) {
		this.colonia = colonia;
	}




}


