package com.shq.entities;
// Generated 17-abr-2018 11:49:46 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Externo generated by hbm2java
 */
@Entity
@Table(name = "externo", catalog = "shq")
public class Externo implements java.io.Serializable {

	private BigDecimal idExterno;
	private Domicilio domicilio;
	private String clave;
	private String correoContacto;
	private Date fechaAlta;
	private String nombre;
	private String nombreContacto;
	private String rfc;
	private String telContacto;
	private String pais;
	private String paisCod;
	private String estado;
	private String estadoCod;
	private String municipio;
	private String munCod;
	private String colonia;
	private String coloniaCod;
	private String cp;
	private String calle;
	private String numInt;
	private String numExt;
	private String referencias;
	private String entreCalles;
	private Boolean activo;
	private String direccionFiscal;
	private String direccionRecoleccion;
	private Set<MovInventario> movInventarios = new HashSet<MovInventario>(0);
	private Set<CotizacionProveedor> cotizacionProveedors = new HashSet<CotizacionProveedor>(0);
	private Set<InvProveedor> invProveedors = new HashSet<InvProveedor>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<CuentaBanco> cuentasBanco = new HashSet<CuentaBanco>(0);

	public Externo() {
	}

	public Externo(BigDecimal idExterno, Boolean activo, Boolean isCliente, Boolean isProveedor) {
		this.idExterno = idExterno;
		this.activo = activo;
	}

	public Externo(BigDecimal idExterno, Domicilio domicilio, String clave, String correoContacto, Date fechaAlta,
			String nombre, String nombreContacto, String rfc, String telContacto, String pais, String paisCod,
			String estado, String estadoCod, String municipio, String munCod, String colonia, String coloniaCod,
			String cp, String calle, String numInt, String numExt, String referencias, String entreCalles,
		    Boolean activo, String direccionFiscal, String direccionRecoleccion, Boolean isCliente,
			Boolean isProveedor, Set<MovInventario> movInventarios, Set<CotizacionProveedor> cotizacionProveedors,
			Set<InvProveedor> invProveedors, Set<Usuario> usuarios, Set<CuentaBanco> cuentasBanco) {
		this.idExterno = idExterno;
		this.domicilio = domicilio;
		this.clave = clave;
		this.correoContacto = correoContacto;
		this.fechaAlta = fechaAlta;
		this.nombre = nombre;
		this.nombreContacto = nombreContacto;
		this.rfc = rfc;
		this.telContacto = telContacto;
		this.pais = pais;
		this.paisCod = paisCod;
		this.estado = estado;
		this.estadoCod = estadoCod;
		this.municipio = municipio;
		this.munCod = munCod;
		this.colonia = colonia;
		this.coloniaCod = coloniaCod;
		this.cp = cp;
		this.calle = calle;
		this.numInt = numInt;
		this.numExt = numExt;
		this.referencias = referencias;
		this.entreCalles = entreCalles;
		this.cuentasBanco = cuentasBanco;
		this.activo = activo;
		this.direccionFiscal = direccionFiscal;
		this.direccionRecoleccion = direccionRecoleccion;
		this.movInventarios = movInventarios;
		this.cotizacionProveedors = cotizacionProveedors;
		this.invProveedors = invProveedors;
		this.usuarios = usuarios;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.AUTO) 
	@Column(name = "id_externo", unique = true, nullable = false, precision = 50, scale = 0)
	public BigDecimal getIdExterno() {
		return this.idExterno;
	}

	public void setIdExterno(BigDecimal idExterno) {
		this.idExterno = idExterno;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_domicilio")
	public Domicilio getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(Domicilio domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "clave", length = 50)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "correo_contacto", length = 100)
	public String getCorreoContacto() {
		return this.correoContacto;
	}

	public void setCorreoContacto(String correoContacto) {
		this.correoContacto = correoContacto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", length = 19)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "nombre_contacto")
	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	@Column(name = "rfc", length = 50)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "tel_contacto", length = 50)
	public String getTelContacto() {
		return this.telContacto;
	}

	public void setTelContacto(String telContacto) {
		this.telContacto = telContacto;
	}

	@Column(name = "pais", length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "pais_cod", length = 20)
	public String getPaisCod() {
		return this.paisCod;
	}

	public void setPaisCod(String paisCod) {
		this.paisCod = paisCod;
	}

	@Column(name = "estado", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "estado_cod", length = 20)
	public String getEstadoCod() {
		return this.estadoCod;
	}

	public void setEstadoCod(String estadoCod) {
		this.estadoCod = estadoCod;
	}

	@Column(name = "municipio", length = 45)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "mun_cod", length = 20)
	public String getMunCod() {
		return this.munCod;
	}

	public void setMunCod(String munCod) {
		this.munCod = munCod;
	}

	@Column(name = "colonia", length = 45)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "colonia_cod", length = 20)
	public String getColoniaCod() {
		return this.coloniaCod;
	}

	public void setColoniaCod(String coloniaCod) {
		this.coloniaCod = coloniaCod;
	}

	@Column(name = "cp", length = 20)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	@Column(name = "calle", length = 500)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "num_int", length = 45)
	public String getNumInt() {
		return this.numInt;
	}

	public void setNumInt(String numInt) {
		this.numInt = numInt;
	}

	@Column(name = "num_ext", length = 45)
	public String getNumExt() {
		return this.numExt;
	}

	public void setNumExt(String numExt) {
		this.numExt = numExt;
	}

	@Column(name = "referencias", length = 500)
	public String getReferencias() {
		return this.referencias;
	}

	public void setReferencias(String referencias) {
		this.referencias = referencias;
	}

	@Column(name = "entre_calles", length = 500)
	public String getEntreCalles() {
		return this.entreCalles;
	}

	public void setEntreCalles(String entreCalles) {
		this.entreCalles = entreCalles;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "direccion_fiscal", length = 500)
	public String getDireccionFiscal() {
		return this.direccionFiscal;
	}

	public void setDireccionFiscal(String direccionFiscal) {
		this.direccionFiscal = direccionFiscal;
	}

	@Column(name = "direccion_recoleccion", length = 500)
	public String getDireccionRecoleccion() {
		return this.direccionRecoleccion;
	}

	public void setDireccionRecoleccion(String direccionRecoleccion) {
		this.direccionRecoleccion = direccionRecoleccion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "externo")
	public Set<MovInventario> getMovInventarios() {
		return this.movInventarios;
	}

	public void setMovInventarios(Set<MovInventario> movInventarios) {
		this.movInventarios = movInventarios;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "externo")
	public Set<CotizacionProveedor> getCotizacionProveedors() {
		return this.cotizacionProveedors;
	}

	public void setCotizacionProveedors(Set<CotizacionProveedor> cotizacionProveedors) {
		this.cotizacionProveedors = cotizacionProveedors;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "externo")
	public Set<InvProveedor> getInvProveedors() {
		return this.invProveedors;
	}

	public void setInvProveedors(Set<InvProveedor> invProveedors) {
		this.invProveedors = invProveedors;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "externo")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "externo")
	public Set<CuentaBanco> getCuentasBanco() {
		return cuentasBanco;
	}

	public void setCuentasBanco(Set<CuentaBanco> cuentasBanco) {
		this.cuentasBanco = cuentasBanco;
	}

}
