package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name = "INVENTARIO", catalog = "shq")
public class Inventario implements java.io.Serializable {

	private int id;
	private int cantidad;
	private BigDecimal costoProm;
	private BigDecimal precioProm;
	private Integer idProducto;

	public Inventario() {
	}

	public Inventario(int id, int cantidad) {
		this.id = id;
		this.cantidad = cantidad;
	}

	public Inventario(int id, int cantidad, BigDecimal costoProm, BigDecimal precioProm, Integer idProducto) {
		this.id = id;
		this.cantidad = cantidad;
		this.costoProm = costoProm;
		this.precioProm = precioProm;
		this.idProducto = idProducto;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "COSTO_PROM")
	public BigDecimal getCostoProm() {
		return this.costoProm;
	}

	public void setCostoProm(BigDecimal costoProm) {
		this.costoProm = costoProm;
	}

	@Column(name = "PRECIO_PROM")
	public BigDecimal getPrecioProm() {
		return this.precioProm;
	}

	public void setPrecioProm(BigDecimal precioProm) {
		this.precioProm = precioProm;
	}

	@Column(name = "ID_PRODUCTO")
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

}
