package com.shq.entities;
// Generated 11-mar-2018 2:54:00 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InventarioVw generated by hbm2java
 */
@Entity
@Table(name = "inventario_vw", catalog = "shq")
public class InventarioVw implements java.io.Serializable {

	private InventarioVwId id;

	public InventarioVw() {
	}

	public InventarioVw(InventarioVwId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", precision = 23, scale = 0)),
			@AttributeOverride(name = "cantidad", column = @Column(name = "CANTIDAD", precision = 34, scale = 0)),
			@AttributeOverride(name = "costoProm", column = @Column(name = "COSTO_PROM", precision = 23, scale = 6)),
			@AttributeOverride(name = "producto", column = @Column(name = "producto")),
			@AttributeOverride(name = "especificaciones", column = @Column(name = "especificaciones")) })
	public InventarioVwId getId() {
		return this.id;
	}

	public void setId(InventarioVwId id) {
		this.id = id;
	}

}
