package com.shq.entities;
// Generated 14-mar-2018 21:20:30 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InventarioLotesVw generated by hbm2java
 */
@Entity
@Table(name = "inventario_lotes_vw", catalog = "shq")
public class InventarioLotesVw implements java.io.Serializable {

	private InventarioLotesVwId id;

	public InventarioLotesVw() {
	}

	public InventarioLotesVw(InventarioLotesVwId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProducto", column = @Column(name = "id_producto", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "lote", column = @Column(name = "lote")),
			@AttributeOverride(name = "cantidad", column = @Column(name = "cantidad", precision = 34, scale = 0)),
			@AttributeOverride(name = "precio", column = @Column(name = "precio", precision = 23, scale = 6)),
			@AttributeOverride(name = "producto", column = @Column(name = "producto")),
			@AttributeOverride(name = "especificaciones", column = @Column(name = "especificaciones")) })
	public InventarioLotesVwId getId() {
		return this.id;
	}

	public void setId(InventarioLotesVwId id) {
		this.id = id;
	}

}
