package com.shq.entities;
// Generated 14-mar-2018 21:20:30 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventarioLotesVwId generated by hbm2java
 */
@Embeddable
public class InventarioLotesVwId implements java.io.Serializable {

	private Long idProducto;
	private String lote;
	private BigDecimal cantidad;
	private BigDecimal precio;
	private String producto;
	private String especificaciones;

	public InventarioLotesVwId() {
	}

	public InventarioLotesVwId(Long idProducto) {
		this.idProducto = idProducto;
	}

	public InventarioLotesVwId(Long idProducto, String lote, BigDecimal cantidad, BigDecimal precio, String producto,
			String especificaciones) {
		this.idProducto = idProducto;
		this.lote = lote;
		this.cantidad = cantidad;
		this.precio = precio;
		this.producto = producto;
		this.especificaciones = especificaciones;
	}

	@Column(name = "id_producto", nullable = false, precision = 11, scale = 0)
	public Long getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Long idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "lote")
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@Column(name = "cantidad", precision = 34, scale = 0)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio", precision = 23, scale = 6)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "producto")
	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	@Column(name = "especificaciones")
	public String getEspecificaciones() {
		return this.especificaciones;
	}

	public void setEspecificaciones(String especificaciones) {
		this.especificaciones = especificaciones;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventarioLotesVwId))
			return false;
		InventarioLotesVwId castOther = (InventarioLotesVwId) other;

		return (this.getIdProducto() == castOther.getIdProducto())
				&& ((this.getLote() == castOther.getLote()) || (this.getLote() != null && castOther.getLote() != null
						&& this.getLote().equals(castOther.getLote())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this.getCantidad() != null
						&& castOther.getCantidad() != null && this.getCantidad().equals(castOther.getCantidad())))
				&& ((this.getPrecio() == castOther.getPrecio()) || (this.getPrecio() != null
						&& castOther.getPrecio() != null && this.getPrecio().equals(castOther.getPrecio())))
				&& ((this.getProducto() == castOther.getProducto()) || (this.getProducto() != null
						&& castOther.getProducto() != null && this.getProducto().equals(castOther.getProducto())))
				&& ((this.getEspecificaciones() == castOther.getEspecificaciones())
						|| (this.getEspecificaciones() != null && castOther.getEspecificaciones() != null
								&& this.getEspecificaciones().equals(castOther.getEspecificaciones())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdProducto().intValue();
		result = 37 * result + (getLote() == null ? 0 : this.getLote().hashCode());
		result = 37 * result + (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		result = 37 * result + (getPrecio() == null ? 0 : this.getPrecio().hashCode());
		result = 37 * result + (getProducto() == null ? 0 : this.getProducto().hashCode());
		result = 37 * result + (getEspecificaciones() == null ? 0 : this.getEspecificaciones().hashCode());
		return result;
	}

}
