package com.shq.entities;
// Generated 11-mar-2018 2:54:00 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventarioVwId generated by hbm2java
 */
@Embeddable
public class InventarioVwId implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal cantidad;
	private BigDecimal costoProm;
	private String producto;
	private String especificaciones;

	public InventarioVwId() {
	}

	public InventarioVwId(BigDecimal id, BigDecimal cantidad, BigDecimal costoProm, String producto,
			String especificaciones) {
		this.id = id;
		this.cantidad = cantidad;
		this.costoProm = costoProm;
		this.producto = producto;
		this.especificaciones = especificaciones;
	}

	@Column(name = "id", precision = 23, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "CANTIDAD", precision = 34, scale = 0)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "COSTO_PROM", precision = 23, scale = 6)
	public BigDecimal getCostoProm() {
		return this.costoProm;
	}

	public void setCostoProm(BigDecimal costoProm) {
		this.costoProm = costoProm;
	}

	@Column(name = "producto")
	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	@Column(name = "especificaciones")
	public String getEspecificaciones() {
		return this.especificaciones;
	}

	public void setEspecificaciones(String especificaciones) {
		this.especificaciones = especificaciones;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventarioVwId))
			return false;
		InventarioVwId castOther = (InventarioVwId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this.getCantidad() != null
						&& castOther.getCantidad() != null && this.getCantidad().equals(castOther.getCantidad())))
				&& ((this.getCostoProm() == castOther.getCostoProm()) || (this.getCostoProm() != null
						&& castOther.getCostoProm() != null && this.getCostoProm().equals(castOther.getCostoProm())))
				&& ((this.getProducto() == castOther.getProducto()) || (this.getProducto() != null
						&& castOther.getProducto() != null && this.getProducto().equals(castOther.getProducto())))
				&& ((this.getEspecificaciones() == castOther.getEspecificaciones())
						|| (this.getEspecificaciones() != null && castOther.getEspecificaciones() != null
								&& this.getEspecificaciones().equals(castOther.getEspecificaciones())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		result = 37 * result + (getCostoProm() == null ? 0 : this.getCostoProm().hashCode());
		result = 37 * result + (getProducto() == null ? 0 : this.getProducto().hashCode());
		result = 37 * result + (getEspecificaciones() == null ? 0 : this.getEspecificaciones().hashCode());
		return result;
	}

}
