package com.shq.entities;
// Generated 17-abr-2018 11:24:42 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InvProductProvVw generated by hbm2java
 */
@Entity
@Table(name = "inv_product_prov_vw", catalog = "shq")
public class InvProductProvVw implements java.io.Serializable {

	private InvProductProvVwId id;

	public InvProductProvVw() {
	}

	public InvProductProvVw(InvProductProvVwId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "producto", column = @Column(name = "producto")),
			@AttributeOverride(name = "precio", column = @Column(name = "precio")),
			@AttributeOverride(name = "cantidad", column = @Column(name = "cantidad", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "proveedor", column = @Column(name = "proveedor")),
			@AttributeOverride(name = "nombreContacto", column = @Column(name = "nombre_contacto")),
			@AttributeOverride(name = "telContacto", column = @Column(name = "tel_contacto", length = 50)),
			@AttributeOverride(name = "correoContacto", column = @Column(name = "correo_contacto", length = 100)) })
	public InvProductProvVwId getId() {
		return this.id;
	}

	public void setId(InvProductProvVwId id) {
		this.id = id;
	}

}
