package com.shq.entities;
// Generated 10-feb-2018 22:29:04 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedimento generated by hbm2java
 */
@Entity
@Table(name = "PEDIMENTO", catalog = "shq")
public class Pedimento implements java.io.Serializable {

	private int id;
	private String aduana;
	private String ciudad;
	private Date fechaEntrada;
	private String pedimento;

	public Pedimento() {
	}

	public Pedimento(int id) {
		this.id = id;
	}

	public Pedimento(int id, String aduana, String ciudad, Date fechaEntrada, String pedimento) {
		this.id = id;
		this.aduana = aduana;
		this.ciudad = ciudad;
		this.fechaEntrada = fechaEntrada;
		this.pedimento = pedimento;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "aduana")
	public String getAduana() {
		return this.aduana;
	}

	public void setAduana(String aduana) {
		this.aduana = aduana;
	}

	@Column(name = "ciudad")
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_ENTRADA", length = 19)
	public Date getFechaEntrada() {
		return this.fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	@Column(name = "pedimento")
	public String getPedimento() {
		return this.pedimento;
	}

	public void setPedimento(String pedimento) {
		this.pedimento = pedimento;
	}

}
