package com.shq.entities;
// Generated 10-feb-2018 4:41:42 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "shq")
public class Person implements java.io.Serializable {

	private Integer personId;
	private String name;
	private String userName;
	private BigDecimal userId;

	public Person() {
	}

	public Person(String userName, BigDecimal userId) {
		this.userName = userName;
		this.userId = userId;
	}

	public Person(String name, String userName, BigDecimal userId) {
		this.name = name;
		this.userName = userName;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "personId", unique = true, nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "name", length = 75)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "user_name", nullable = false, length = 75)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_id", nullable = false, precision = 50, scale = 0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

}
