package com.shq.entities;
// Generated 10-feb-2018 21:58:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTO", catalog = "shq")
public class Producto implements java.io.Serializable {

	private int id;
	private String clave;
	private String especificaciones;
	private String producto;
	private int impuesto;

	public Producto() {
	}

	public Producto(int id) {
		this.id = id;
	}

	public Producto(int id, String clave, String especificaciones, String producto) {
		this.id = id;
		this.clave = clave;
		this.especificaciones = especificaciones;
		this.producto = producto;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "clave")
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "especificaciones")
	public String getEspecificaciones() {
		return this.especificaciones;
	}

	public void setEspecificaciones(String especificaciones) {
		this.especificaciones = especificaciones;
	}

	@Column(name = "producto")
	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public int getImpuesto() {
		return impuesto;
	}

	public void setImpuesto(int impuesto) {
		this.impuesto = impuesto;
	}

}
