package com.shq.entities;
// Generated 09-abr-2018 5:40:18 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoCotProveedor generated by hbm2java
 */
@Entity
@Table(name = "producto_cot_proveedor", catalog = "shq")
public class ProductoCotProveedor implements java.io.Serializable {

	private long id;
	private CotizacionProveedor cotizacionProveedor;
	private Producto producto;
	private long cantidad;
	private Long costo;
	private Long tiempoEntrega;
	private Long dispMensual;
	private String moneda;

	public ProductoCotProveedor() {
	}

	public ProductoCotProveedor(long id, CotizacionProveedor cotizacionProveedor, Producto producto, long cantidad) {
		this.id = id;
		this.cotizacionProveedor = cotizacionProveedor;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	public ProductoCotProveedor(long id, CotizacionProveedor cotizacionProveedor, Producto producto, long cantidad,
			Long costo, Long tiempoEntrega, Long dispMensual) {
		this.id = id;
		this.cotizacionProveedor = cotizacionProveedor;
		this.producto = producto;
		this.cantidad = cantidad;
		this.costo = costo;
		this.tiempoEntrega = tiempoEntrega;
		this.dispMensual = dispMensual;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) 
	@Column(name = "id", unique = true, nullable = false, precision = 11, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cot_proveedor", nullable = false)
	public CotizacionProveedor getCotizacionProveedor() {
		return this.cotizacionProveedor;
	}

	public void setCotizacionProveedor(CotizacionProveedor cotizacionProveedor) {
		this.cotizacionProveedor = cotizacionProveedor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad", nullable = false, precision = 11, scale = 0)
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "costo", precision = 11, scale = 0)
	public Long getCosto() {
		return this.costo;
	}

	public void setCosto(Long costo) {
		this.costo = costo;
	}

	@Column(name = "tiempo_entrega", precision = 11, scale = 0)
	public Long getTiempoEntrega() {
		return this.tiempoEntrega;
	}

	public void setTiempoEntrega(Long tiempoEntrega) {
		this.tiempoEntrega = tiempoEntrega;
	}

	@Column(name = "disp_mensual", precision = 11, scale = 0)
	public Long getDispMensual() {
		return this.dispMensual;
	}

	public void setDispMensual(Long dispMensual) {
		this.dispMensual = dispMensual;
	}

	@Column(name = "moneda", length = 45)
	public String getMoneda() {
		return moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

}
