package com.shq.entities;
// Generated 20-mar-2018 11:58:35 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductoSolCotizacionParc generated by hbm2java
 */
@Entity
@Table(name = "producto_sol_cotizacion_parc", catalog = "shq")
public class ProductoSolCotizacionParc implements java.io.Serializable {

	private ProductoSolCotizacionParcId id;

	public ProductoSolCotizacionParc() {
	}

	public ProductoSolCotizacionParc(ProductoSolCotizacionParcId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSolicitud", column = @Column(name = "id_solicitud", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "idProducto", column = @Column(name = "id_producto", precision = 11, scale = 0)),
			@AttributeOverride(name = "producto", column = @Column(name = "producto")),
			@AttributeOverride(name = "cantidadSolicitada", column = @Column(name = "cantidad_solicitada", precision = 11, scale = 0)),
			@AttributeOverride(name = "cantidadAlmacen", column = @Column(name = "cantidad_almacen", precision = 33, scale = 0)),
			@AttributeOverride(name = "cantidadCotizar", column = @Column(name = "cantidad_cotizar", precision = 34, scale = 0)) })
	public ProductoSolCotizacionParcId getId() {
		return this.id;
	}

	public void setId(ProductoSolCotizacionParcId id) {
		this.id = id;
	}

}
