package com.shq.entities;
// Generated 12-mar-2018 3:16:01 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoSolCotizacion generated by hbm2java
 */
@Entity
@Table(name = "producto_sol_cotizacion", catalog = "shq")
public class ProductoSolCotizacion implements java.io.Serializable {

	private Long id;
	private SolCotizacion solCotizacion;
	private Producto producto;
	private Long cantidad;


	public ProductoSolCotizacion() {
	}

	public ProductoSolCotizacion(Long id, SolCotizacion solCotizacion, Producto producto) {
		this.id = id;
		this.solCotizacion = solCotizacion;
		this.producto = producto;
	}

	public ProductoSolCotizacion(Long id, SolCotizacion solCotizacion, Producto producto, Long cantidad,Long cantidadInventario) {
		this.id = id;
		this.solCotizacion = solCotizacion;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) 
	@Column(name = "id", unique = true, nullable = false, precision = 11, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_solicitud", nullable = false)
	public SolCotizacion getSolCotizacion() {
		return this.solCotizacion;
	}

	public void setSolCotizacion(SolCotizacion solCotizacion) {
		this.solCotizacion = solCotizacion;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad", precision = 11, scale = 0)
	public Long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Long cantidad) {
		this.cantidad = cantidad;
	}
	

}
