package com.shq.entities;
// Generated 20-mar-2018 11:58:35 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductoSolCotizacionParcId generated by hbm2java
 */
@Embeddable
public class ProductoSolCotizacionParcId implements java.io.Serializable {

	private Long idSolicitud;
	private Long idProducto;
	private String producto;
	private Long cantidadSolicitada;
	private BigDecimal cantidadAlmacen;
	private BigDecimal cantidadCotizar;

	public ProductoSolCotizacionParcId() {
	}

	public ProductoSolCotizacionParcId(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	public ProductoSolCotizacionParcId(Long idSolicitud, Long idProducto, String producto, Long cantidadSolicitada,
			BigDecimal cantidadAlmacen, BigDecimal cantidadCotizar) {
		this.idSolicitud = idSolicitud;
		this.idProducto = idProducto;
		this.producto = producto;
		this.cantidadSolicitada = cantidadSolicitada;
		this.cantidadAlmacen = cantidadAlmacen;
		this.cantidadCotizar = cantidadCotizar;
	}

	@Column(name = "id_solicitud", nullable = false, precision = 11, scale = 0)
	public Long getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	@Column(name = "id_producto", precision = 11, scale = 0)
	public Long getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Long idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "producto")
	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad_solicitada", precision = 11, scale = 0)
	public Long getCantidadSolicitada() {
		return this.cantidadSolicitada;
	}

	public void setCantidadSolicitada(Long cantidadSolicitada) {
		this.cantidadSolicitada = cantidadSolicitada;
	}

	@Column(name = "cantidad_almacen", precision = 33, scale = 0)
	public BigDecimal getCantidadAlmacen() {
		return this.cantidadAlmacen;
	}

	public void setCantidadAlmacen(BigDecimal cantidadAlmacen) {
		this.cantidadAlmacen = cantidadAlmacen;
	}

	@Column(name = "cantidad_cotizar", precision = 34, scale = 0)
	public BigDecimal getCantidadCotizar() {
		return this.cantidadCotizar;
	}

	public void setCantidadCotizar(BigDecimal cantidadCotizar) {
		this.cantidadCotizar = cantidadCotizar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductoSolCotizacionParcId))
			return false;
		ProductoSolCotizacionParcId castOther = (ProductoSolCotizacionParcId) other;

		return (this.getIdSolicitud() == castOther.getIdSolicitud())
				&& ((this.getIdProducto() == castOther.getIdProducto()) || (this.getIdProducto() != null
						&& castOther.getIdProducto() != null && this.getIdProducto().equals(castOther.getIdProducto())))
				&& ((this.getProducto() == castOther.getProducto()) || (this.getProducto() != null
						&& castOther.getProducto() != null && this.getProducto().equals(castOther.getProducto())))
				&& ((this.getCantidadSolicitada() == castOther.getCantidadSolicitada())
						|| (this.getCantidadSolicitada() != null && castOther.getCantidadSolicitada() != null
								&& this.getCantidadSolicitada().equals(castOther.getCantidadSolicitada())))
				&& ((this.getCantidadAlmacen() == castOther.getCantidadAlmacen())
						|| (this.getCantidadAlmacen() != null && castOther.getCantidadAlmacen() != null
								&& this.getCantidadAlmacen().equals(castOther.getCantidadAlmacen())))
				&& ((this.getCantidadCotizar() == castOther.getCantidadCotizar())
						|| (this.getCantidadCotizar() != null && castOther.getCantidadCotizar() != null
								&& this.getCantidadCotizar().equals(castOther.getCantidadCotizar())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSolicitud().intValue();
		result = 37 * result + (getIdProducto() == null ? 0 : this.getIdProducto().hashCode());
		result = 37 * result + (getProducto() == null ? 0 : this.getProducto().hashCode());
		result = 37 * result + (getCantidadSolicitada() == null ? 0 : this.getCantidadSolicitada().hashCode());
		result = 37 * result + (getCantidadAlmacen() == null ? 0 : this.getCantidadAlmacen().hashCode());
		result = 37 * result + (getCantidadCotizar() == null ? 0 : this.getCantidadCotizar().hashCode());
		return result;
	}

}
