package com.shq.entities;
// Generated 08-abr-2018 18:46:02 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolCotizacion generated by hbm2java
 */
@Entity
@Table(name = "sol_cotizacion", catalog = "shq")
public class SolCotizacion implements java.io.Serializable {

	private long id;
	private Usuario usuarioByIdComprador;
	private Usuario usuarioByIdVendedor;
	private Usuario usuarioByIdExterno;
	private String nota;
	private String status;
	private Date fechaSol;
	private String nombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String telefono;
	private String correo;
	private String dondeEntregar;
	private String pais;
	private String estado;
	private String colonia;
	private String cp;
	private String calle;
	private String referencias;
	private String numInt;
	private String numExt;
	private Date fechaEntrega;
	private String municipio;
	private String msjCotizCliente;
	private String paisFiscal;
	private String munFiscal;
	private String estadoFiscal;
	private String coloniaFiscal;
	private String cpFiscal;
	private String calleFiscal;
	private String numExtFiscal;
	private String numIntFiscal;
	private String rfc;
	private String metodoPago;
	private String valor;
	private String fletera;
	private String direccionEntrega;
	private String direccionFiscal;
	private Set<ProductoSolCotizacion> productoSolCotizacions = new HashSet<ProductoSolCotizacion>(0);
	private Set<ApartadosCotizacion> apartadosCotizacions = new HashSet<ApartadosCotizacion>(0);
	private int codStatus;

	public SolCotizacion() {
	}

	public SolCotizacion(long id, String status, Date fechaSol, String nombre, String apellidoPaterno,
			String apellidoMaterno, String telefono, String correo, String dondeEntregar, String pais, String estado,
			String colonia, String cp, String calle, String numExt, Date fechaEntrega, String municipio,int codStatus) {
		this.id = id;
		this.status = status;
		this.fechaSol = fechaSol;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.telefono = telefono;
		this.correo = correo;
		this.dondeEntregar = dondeEntregar;
		this.pais = pais;
		this.estado = estado;
		this.colonia = colonia;
		this.cp = cp;
		this.calle = calle;
		this.numExt = numExt;
		this.fechaEntrega = fechaEntrega;
		this.municipio = municipio;
		this.codStatus = codStatus;
	}

	public SolCotizacion(long id, Usuario usuarioByIdComprador, Usuario usuarioByIdVendedor, Usuario usuarioByIdExterno,
			String nota, String status, Date fechaSol, String nombre, String apellidoPaterno, String apellidoMaterno,
			String telefono, String correo, String dondeEntregar, String pais, String estado, String colonia, String cp,
			String calle, String referencias, String numInt, String numExt, Date fechaEntrega, String municipio,
			String msjCotizCliente, String paisFiscal, String munFiscal, String estadoFiscal, String coloniaFiscal,
			String cpFiscal, String calleFiscal, String numExtFiscal, String numIntFiscal, String rfc,
			String metodoPago, String valor, String fletera, Set<ProductoSolCotizacion> productoSolCotizacions,
			Set<ApartadosCotizacion> apartadosCotizacions,int codStatus) {
		this.id = id;
		this.usuarioByIdComprador = usuarioByIdComprador;
		this.usuarioByIdVendedor = usuarioByIdVendedor;
		this.usuarioByIdExterno = usuarioByIdExterno;
		this.nota = nota;
		this.status = status;
		this.fechaSol = fechaSol;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.telefono = telefono;
		this.correo = correo;
		this.dondeEntregar = dondeEntregar;
		this.pais = pais;
		this.estado = estado;
		this.colonia = colonia;
		this.cp = cp;
		this.calle = calle;
		this.referencias = referencias;
		this.numInt = numInt;
		this.numExt = numExt;
		this.fechaEntrega = fechaEntrega;
		this.municipio = municipio;
		this.msjCotizCliente = msjCotizCliente;
		this.paisFiscal = paisFiscal;
		this.munFiscal = munFiscal;
		this.estadoFiscal = estadoFiscal;
		this.coloniaFiscal = coloniaFiscal;
		this.cpFiscal = cpFiscal;
		this.calleFiscal = calleFiscal;
		this.numExtFiscal = numExtFiscal;
		this.numIntFiscal = numIntFiscal;
		this.rfc = rfc;
		this.metodoPago = metodoPago;
		this.valor = valor;
		this.fletera = fletera;
		this.productoSolCotizacions = productoSolCotizacions;
		this.apartadosCotizacions = apartadosCotizacions;
		this.codStatus = codStatus;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) 
	@Column(name = "id", unique = true, nullable = false, precision = 11, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_comprador")
	public Usuario getUsuarioByIdComprador() {
		return this.usuarioByIdComprador;
	}

	public void setUsuarioByIdComprador(Usuario usuarioByIdComprador) {
		this.usuarioByIdComprador = usuarioByIdComprador;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_vendedor")
	public Usuario getUsuarioByIdVendedor() {
		return this.usuarioByIdVendedor;
	}

	public void setUsuarioByIdVendedor(Usuario usuarioByIdVendedor) {
		this.usuarioByIdVendedor = usuarioByIdVendedor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_externo")
	public Usuario getUsuarioByIdExterno() {
		return this.usuarioByIdExterno;
	}

	public void setUsuarioByIdExterno(Usuario usuarioByIdExterno) {
		this.usuarioByIdExterno = usuarioByIdExterno;
	}

	@Column(name = "nota", length = 45)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_sol", nullable = false, length = 19)
	public Date getFechaSol() {
		return this.fechaSol;
	}

	public void setFechaSol(Date fechaSol) {
		this.fechaSol = fechaSol;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido_paterno", nullable = false, length = 45)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "apellido_materno", nullable = false, length = 45)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "telefono", nullable = false, length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "correo", nullable = false, length = 45)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "donde_entregar", nullable = false, length = 45)
	public String getDondeEntregar() {
		return this.dondeEntregar;
	}

	public void setDondeEntregar(String dondeEntregar) {
		this.dondeEntregar = dondeEntregar;
	}

	@Column(name = "pais", nullable = false, length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "estado", nullable = false, length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "colonia", nullable = false, length = 45)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "cp", nullable = false, length = 10)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	@Column(name = "calle", nullable = false, length = 45)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "referencias", length = 45)
	public String getReferencias() {
		return this.referencias;
	}

	public void setReferencias(String referencias) {
		this.referencias = referencias;
	}

	@Column(name = "num_int", length = 45)
	public String getNumInt() {
		return this.numInt;
	}

	public void setNumInt(String numInt) {
		this.numInt = numInt;
	}

	@Column(name = "num_ext", nullable = false, length = 45)
	public String getNumExt() {
		return this.numExt;
	}

	public void setNumExt(String numExt) {
		this.numExt = numExt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_entrega", nullable = false, length = 19)
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	@Column(name = "municipio", nullable = false, length = 45)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "msj_cotiz_cliente", length = 5000)
	public String getMsjCotizCliente() {
		return this.msjCotizCliente;
	}

	public void setMsjCotizCliente(String msjCotizCliente) {
		this.msjCotizCliente = msjCotizCliente;
	}

	@Column(name = "pais_fiscal", length = 45)
	public String getPaisFiscal() {
		return this.paisFiscal;
	}

	public void setPaisFiscal(String paisFiscal) {
		this.paisFiscal = paisFiscal;
	}

	@Column(name = "mun_fiscal", length = 45)
	public String getMunFiscal() {
		return this.munFiscal;
	}

	public void setMunFiscal(String munFiscal) {
		this.munFiscal = munFiscal;
	}

	@Column(name = "estado_fiscal", length = 45)
	public String getEstadoFiscal() {
		return this.estadoFiscal;
	}

	public void setEstadoFiscal(String estadoFiscal) {
		this.estadoFiscal = estadoFiscal;
	}

	@Column(name = "colonia_fiscal", length = 45)
	public String getColoniaFiscal() {
		return this.coloniaFiscal;
	}

	public void setColoniaFiscal(String coloniaFiscal) {
		this.coloniaFiscal = coloniaFiscal;
	}

	@Column(name = "cp_fiscal", length = 45)
	public String getCpFiscal() {
		return this.cpFiscal;
	}

	public void setCpFiscal(String cpFiscal) {
		this.cpFiscal = cpFiscal;
	}

	@Column(name = "calle_fiscal", length = 45)
	public String getCalleFiscal() {
		return this.calleFiscal;
	}

	public void setCalleFiscal(String calleFiscal) {
		this.calleFiscal = calleFiscal;
	}

	@Column(name = "num_ext_fiscal", length = 45)
	public String getNumExtFiscal() {
		return this.numExtFiscal;
	}

	public void setNumExtFiscal(String numExtFiscal) {
		this.numExtFiscal = numExtFiscal;
	}

	@Column(name = "num_int_fiscal", length = 45)
	public String getNumIntFiscal() {
		return this.numIntFiscal;
	}

	public void setNumIntFiscal(String numIntFiscal) {
		this.numIntFiscal = numIntFiscal;
	}

	@Column(name = "rfc", length = 45)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "metodo_pago", length = 45)
	public String getMetodoPago() {
		return this.metodoPago;
	}

	public void setMetodoPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

	@Column(name = "valor", length = 45)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "fletera", length = 45)
	public String getFletera() {
		return this.fletera;
	}

	public void setFletera(String fletera) {
		this.fletera = fletera;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "solCotizacion")
	public Set<ProductoSolCotizacion> getProductoSolCotizacions() {
		return this.productoSolCotizacions;
	}

	public void setProductoSolCotizacions(Set<ProductoSolCotizacion> productoSolCotizacions) {
		this.productoSolCotizacions = productoSolCotizacions;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "solCotizacion")
	public Set<ApartadosCotizacion> getApartadosCotizacions() {
		return this.apartadosCotizacions;
	}

	public void setApartadosCotizacions(Set<ApartadosCotizacion> apartadosCotizacions) {
		this.apartadosCotizacions = apartadosCotizacions;
	}

	@Column(name = "direccion_entrega", length = 500)
	public String getDireccionEntrega() {
		return direccionEntrega;
	}

	public void setDireccionEntrega(String direccionEntrega) {
		this.direccionEntrega = direccionEntrega;
	}

	@Column(name = "direccion_fiscal", length = 500)
	public String getDireccionFiscal() {
		return direccionFiscal;
	}

	public void setDireccionFiscal(String direccionFiscal) {
		this.direccionFiscal = direccionFiscal;
	}

	@Column(name = "cod_status")
	public int getCodStatus() {
		return codStatus;
	}

	public void setCodStatus(int codStatus) {
		this.codStatus = codStatus;
	}

	

}
